// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNVO7aaHAVsLbpR2ehHB6Wfzr3noKlvQM',
    appId: '1:648126554082:web:278a2149b4398e5fefe3bb',
    messagingSenderId: '648126554082',
    projectId: 'telemed-flutter',
    authDomain: 'telemed-flutter.firebaseapp.com',
    storageBucket: 'telemed-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR0K4jxdxGUsZtSsLhCqwE6SZ-Ro-OgGI',
    appId: '1:648126554082:android:50bc98cb54c69c40efe3bb',
    messagingSenderId: '648126554082',
    projectId: 'telemed-flutter',
    storageBucket: 'telemed-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr06f8GDLuYaRgTjbTkDz74RVnGLkSSjs',
    appId: '1:648126554082:ios:8729d345f4433b6eefe3bb',
    messagingSenderId: '648126554082',
    projectId: 'telemed-flutter',
    storageBucket: 'telemed-flutter.appspot.com',
    iosClientId: '648126554082-a4mdmfq1pl442hiflmtpa3lcskvpgb24.apps.googleusercontent.com',
    iosBundleId: 'com.telemed.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr06f8GDLuYaRgTjbTkDz74RVnGLkSSjs',
    appId: '1:648126554082:ios:4f3f59800c410d2cefe3bb',
    messagingSenderId: '648126554082',
    projectId: 'telemed-flutter',
    storageBucket: 'telemed-flutter.appspot.com',
    iosClientId: '648126554082-5e91v9embd416d3knkmh0ai02qekmj0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.telemed.RunnerTests',
  );
}
